### ISSUE TITLE
BCM94360CS2AX in m.2 slot?

### ISSUE THREAD

**Issue by jsybert** [notthebee/t440p-airport#1]
is there a way to use the BCM94360CS2AX airport/bluetooth card in the m.2. slot instead of modifying the laptop to use the adapter in the wifi card slot?

**Comment by notthebee** [comment]
From what I know, the LTE modem slot doesn't provide PCIe connectivity, so no.
You can still use DW1560/DW1830

**Comment by jsybert** [comment]
ok, thank you wolfgang.  great tutorial on this and on the t440p hackintosh.  great work!
