### ISSUE TITLE
catalina not detecting air card

### ISSUE THREAD

**Issue by jsybert** [notthebee/t440p-airport#2]
i bought this:

https://www.ebay.com/itm/Apple-MacBook-Air-MC965LL-A-Bluetooth-WiFi-Wireless-Card-A1369-607-8821/264592080545?ssPageName=STRK%3AMEBIDX%3AIT&_trksid=p2057872.m2749.l2649

and have it in this:

https://www.ebay.com/itm/BCM94360CS2-BCM943224PCIEBT2-12-6-Pin-WIFI-Wireless-Card-Module-to-NGFF-M-2/283111724041?ssPageName=STRK%3AMEBIDX%3AIT&_trksid=p2057872.m2749.l2649

with the bios whitelist removed and installed using most of your method (i have the ethernet port removed)

and catalina doesn't detect it.  is there a kext that is needed?

**Comment by jsybert** [comment]
forgot to mention...  it works properly in windows 10...

**Comment by devnetomartins** [comment]
I believe that the problem must be this airport that you are using. Researching, I saw that it is used in the macbook air until 2011. These macbooks are not compatible with catalina.
